# Generated by Django 5.1.3 on 2024-11-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('centro_costo', models.IntegerField()),
                ('ingreso', models.DateField()),
                ('antiguedad', models.FloatField()),
                ('ultima_fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('cargo', models.CharField(max_length=255)),
                ('tipo_empleado', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_votante', models.CharField(max_length=20, unique=True)),
                ('cualidad', models.CharField(choices=[('Puntualidad', 'Puntualidad'), ('Eficiencia', 'Eficiencia'), ('Compañerismo', 'Compañerismo'), ('Compromiso', 'Compromiso'), ('Antigüedad mayor a 3 años', 'Antigüedad mayor a 3 años')], max_length=50)),
                ('trabajador_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacion.trabajador')),
            ],
        ),
    ]
