# Generated by Django 5.1.3 on 2024-11-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='documento_votante',
        ),
    ]
