# Generated by Django 5.1.3 on 2024-11-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0002_remove_trabajador_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='cualidad',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='trabajador_candidato',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='documento',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='votacion.trabajador'),
        ),
        migrations.AddField(
            model_name='voto',
            name='fecha_voto',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_realizados', to='votacion.trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='antiguedad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='centro_costo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_empleado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='ultima_fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
